DROP TABLE IF EXISTS sake_drink_styles CASCADE;
DROP TABLE IF EXISTS drink_styles CASCADE;
DROP TABLE IF EXISTS sakes CASCADE;
DROP TABLE IF EXISTS breweries CASCADE;
DROP TABLE IF EXISTS sake_types CASCADE;
