// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// 酒造
type Brewery struct {
	ID int32 `db:"id" json:"id"`
	// 酒造名
	Name string `db:"name" json:"name"`
	// 所在国
	OriginCountry string `db:"origin_country" json:"origin_country"`
	// 所在地域
	OriginRegion *string `db:"origin_region" json:"origin_region"`
	// 座標(任意)
	Position interface{} `db:"position" json:"position"`
	// 作成日時
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	// 更新日時
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

// 飲み方(マスター)
type DrinkStyle struct {
	ID int32 `db:"id" json:"id"`
	// 酒の飲み方
	Name string `db:"name" json:"name"`
	// 詳細説明
	Description *string `db:"description" json:"description"`
	// 作成日時
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	// 更新日時
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

// 酒
type Sake struct {
	ID int32 `db:"id" json:"id"`
	// 酒の種類id
	TypeID int32 `db:"type_id" json:"type_id"`
	// 酒造id
	BreweryID int32 `db:"brewery_id" json:"brewery_id"`
	// 酒名
	Name string `db:"name" json:"name"`
	// アルコール度数(%)
	Abv pgtype.Numeric `db:"abv" json:"abv"`
	// 味の特徴
	TasteNotes string `db:"taste_notes" json:"taste_notes"`
	// 感想
	Memo *string `db:"memo" json:"memo"`
	// 作成日時
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	// 更新日時
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

// 酒-飲み方(中間テーブル)
type SakeDrinkStyle struct {
	// 酒id
	SakeID int32 `db:"sake_id" json:"sake_id"`
	// 酒の飲み方id
	DrinkStyleID int32 `db:"drink_style_id" json:"drink_style_id"`
}

// 酒の種類
type SakeType struct {
	ID int32 `db:"id" json:"id"`
	// 酒の種類の名前
	Name string `db:"name" json:"name"`
	// 作成日時
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	// 更新日時
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}
