// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountSakes(ctx context.Context, arg CountSakesParams) (int64, error)
	GetBrewery(ctx context.Context, id int32) (Brewery, error)
	GetDrinkStylesBySakeID(ctx context.Context, sakeID int32) ([]DrinkStyle, error)
	GetSakeType(ctx context.Context, id int32) (SakeType, error)
	ListSakes(ctx context.Context, arg ListSakesParams) ([]Sake, error)
}

var _ Querier = (*Queries)(nil)
